### PR TITLE
Add Armoury Crate and AURA hotkeys

### PR DESCRIPTION
**Pull request by misaka19465**

### CODE REVIEW

**Comment by KastB** [comment]
Is there possibly a typo? "Armoury Create" vs "Armoury Crate"?

**Comment by ldrahnik** [comment]
I do not recommend using at least `KEY_PROG2`. Why? `KEY_PROG2` key is used on my 2v1 Asus laptop ZenBook UP5401EA for changing to tablet mode and back to laptop mode so if I understand well this change would send another `KEY_PROG2` from the same device and could confuse 2v1 fliplock drivers depending on that value. Correct me if I missed something.

Capture of events during flipping to tablet mode and back:

```
$ sudo libinput debug-events
...
-event4   DEVICE_ADDED     Asus WMI hotkeys                  seat0 default group11 cap:k
...
-event25  SWITCH_TOGGLE    +0.000s	switch tablet-mode state 1
-event4   KEYBOARD_KEY     +0.001s	KEY_PROG2 (149) pressed
 event4   KEYBOARD_KEY     +0.001s	KEY_PROG2 (149) released
-event25  SWITCH_TOGGLE    +1.100s	switch tablet-mode state 0
-event4   KEYBOARD_KEY     +1.103s	KEY_PROG2 (149) pressed
 event4   KEYBOARD_KEY     +1.103s	KEY_PROG2 (149) released
```

**Comment by misaka19465** [comment]
There IS a typo, sorry. And which key should I use? I couldn't find fit keys.

**Comment by misaka19465** [comment]
I changed these keys into PROG3 and PROG4, hope there won't be a conflict again.

**Pull request merged**
